project:
  type: website
  output-dir: docs

website:
  title: "Alison Obright"
  navbar:
    left:
      - href: index.qmd
        text: About Alison
      - href: projects.qmd
        text: Active Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: 
      light: journal
      dark: vapor
    css: styles.css
    toc: true
  pdf:
    documentclass: report
  docx: default
  pptx: default

